services:
  - type: web
    name: black-meet-signaling
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PHP_BASE_URL
        sync: false

  - type: web
    name: black-meet-web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SIGNALING_URL
        sync: false
