// Tailwind JIT build config (self-hosted; no CDN). Run: npx tailwindcss -c tailwind.config.js -i tools/tailwind.src.css -o assets/css/tailwind.css --minify
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
'./server/views/**/*.ejs',
    './assets/js/**/*.js',
    './shared/**/*.js',
  ],
  safelist: [
    'w-9 h-9', 'w-10 h-10', 'w-11 h-11', 'w-12 h-12',
    'bg-secondary-container text-on-secondary-container',
    'bg-error-container/80 text-on-error-container',
    'bg-primary-container/40',
    'rounded-tr-sm', 'rounded-tl-sm',
    'bg-warning',
  ],
  theme: {
    extend: {
      colors: {
"outline-variant": "rgb(var(--bm-outline-variant) / <alpha-value>)",
        "background": "rgb(var(--bm-background) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--bm-surface-container-highest) / <alpha-value>)",
        "tertiary-container": "rgb(var(--bm-tertiary-container) / <alpha-value>)",
        "on-surface": "rgb(var(--bm-on-surface) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--bm-surface-container-lowest) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--bm-primary-fixed-dim) / <alpha-value>)",
        "inverse-primary": "rgb(var(--bm-inverse-primary) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--bm-on-tertiary-fixed) / <alpha-value>)",
        "primary-container": "rgb(var(--bm-primary-container) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--bm-on-tertiary-container) / <alpha-value>)",
        "error": "rgb(var(--bm-error) / <alpha-value>)",
        "inverse-surface": "rgb(var(--bm-inverse-surface) / <alpha-value>)",
        "primary": "rgb(var(--bm-primary) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--bm-on-primary-fixed-variant) / <alpha-value>)",
        "surface-dim": "rgb(var(--bm-surface-dim) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--bm-on-secondary-container) / <alpha-value>)",
        "secondary-container": "rgb(var(--bm-secondary-container) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--bm-on-surface-variant) / <alpha-value>)",
        "secondary": "rgb(var(--bm-secondary) / <alpha-value>)",
        "outline": "rgb(var(--bm-outline) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--bm-tertiary-fixed) / <alpha-value>)",
        "error-container": "rgb(var(--bm-error-container) / <alpha-value>)",
        "on-secondary": "rgb(var(--bm-on-secondary) / <alpha-value>)",
        "primary-fixed": "rgb(var(--bm-primary-fixed) / <alpha-value>)",
        "on-error-container": "rgb(var(--bm-on-error-container) / <alpha-value>)",
        "on-tertiary": "rgb(var(--bm-on-tertiary) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--bm-on-secondary-fixed-variant) / <alpha-value>)",
        "surface-variant": "rgb(var(--bm-surface-variant) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--bm-inverse-on-surface) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--bm-on-secondary-fixed) / <alpha-value>)",
        "surface-bright": "rgb(var(--bm-surface-bright) / <alpha-value>)",
        "on-background": "rgb(var(--bm-on-background) / <alpha-value>)",
        "on-error": "rgb(var(--bm-on-error) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--bm-tertiary-fixed-dim) / <alpha-value>)",
        "surface-container-low": "rgb(var(--bm-surface-container-low) / <alpha-value>)",
        "surface": "rgb(var(--bm-surface) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--bm-secondary-fixed) / <alpha-value>)",
        "tertiary": "rgb(var(--bm-tertiary) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--bm-on-tertiary-fixed-variant) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--bm-secondary-fixed-dim) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--bm-on-primary-fixed) / <alpha-value>)",
        "surface-tint": "rgb(var(--bm-surface-tint) / <alpha-value>)",
        "surface-container": "rgb(var(--bm-surface-container) / <alpha-value>)",
        "on-primary": "rgb(var(--bm-on-primary) / <alpha-value>)",
        "surface-container-high": "rgb(var(--bm-surface-container-high) / <alpha-value>)",
        "on-primary-container": "rgb(var(--bm-on-primary-container) / <alpha-value>)"
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: { "grid-margin":"24px","grid-gutter":"16px","xs":"4px","sm":"8px","md":"16px","lg":"24px","xl":"40px","base":"4px" },
      fontFamily: {
        "body-md":["Entezar","Tahoma","Arial","sans-serif"], "body-lg":["Entezar","Tahoma","Arial","sans-serif"],
        "body-sm":["Entezar","Tahoma","Arial","sans-serif"], "headline-md":["Digi Ghaf Bold","Entezar","Tahoma","Arial","sans-serif"],
        "headline-lg":["Digi Ghaf Bold","Entezar","Tahoma","Arial","sans-serif"], "display-md":["Digi Ghaf Bold","Entezar","Tahoma","Arial","sans-serif"],
        "display-lg":["Digi Ghaf Bold","Entezar","Tahoma","Arial","sans-serif"], "label-md":["Entezar","Tahoma","Arial","sans-serif"], "label-sm":["Entezar","Tahoma","Arial","sans-serif"]
      },
      fontSize: {
        "body-md":["16px",{"lineHeight":"24px","fontWeight":"400"}],
        "body-lg":["18px",{"lineHeight":"28px","fontWeight":"400"}],
        "body-sm":["14px",{"lineHeight":"20px","fontWeight":"400"}],
        "headline-md":["20px",{"lineHeight":"28px","fontWeight":"600"}],
        "headline-lg":["28px",{"lineHeight":"36px","fontWeight":"600"}],
        "display-md":["36px",{"lineHeight":"44px","letterSpacing":"-0.02em","fontWeight":"700"}],
        "display-lg":["48px",{"lineHeight":"56px","letterSpacing":"-0.02em","fontWeight":"700"}],
        "label-md":["14px",{"lineHeight":"20px","letterSpacing":"0.05em","fontWeight":"500"}],
        "label-sm":["12px",{"lineHeight":"16px","letterSpacing":"0.05em","fontWeight":"500"}]
      }
    }
  },
  plugins: [require('@tailwindcss/forms')],
};